apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flight-api-hub
  name: flight-api-hub
  namespace: sit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-api-hub
  template:
    metadata:
      labels:
        app: flight-api-hub
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: flight-api-hub-configmap-dev
        image: tripotadevacr.azurecr.io/flight-api-hub:17561
        imagePullPolicy: Always
        name: flight-api-hub
        ports:
        - containerPort: 808
        resources:
          limits:
            memory: 1500Mi
          requests:
            memory: 1500Mi
      imagePullSecrets:
      - name: tripota-acr-secret
      #nodeName: tripota-vm-dev-02
