apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: traefik
  labels:
    app: flight-api-hub
  name: flight-api-hub
  namespace: sit
spec:
  rules:
  - host: duy.com
    http:
      paths:
      - backend:
          service:
            name: flight-api-hub-svc
            port: 
              number: 8080
        path: /
        pathType: Prefix  
  tls:
  - hosts:
    - duy.com
    secretName: flight-api-hub-tls
