apiVersion: v1
kind: Service
metadata:
  name: hotel-api-hub-svc
  namespace: sit
spec:
  selector:
    app: hotel-api-hub
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
